# Generated by Django 5.0.7 on 2024-07-15 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vet',
            old_name='name',
            new_name='title',
        ),
    ]
